# Generated by Django 3.1.1 on 2020-12-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='Teste', max_length=100),
        ),
    ]
