# Generated by Django 3.1.1 on 2020-12-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
    ]
